### ISSUE TITLE
Error on "Rebuild basic materials"

### ISSUE THREAD

**Issue by Remtou** [soupday/cc_blender_tools#102]
Hello,

I have an error when I want to rebuild basic materials from CC model imported in Blender:
- I use Blender 3.3.0 and Character Creator 4 on PC Windows 10.
- I export the FBX model from CC4 using all recommended parameter from tutorial (Blender preset, no embed texture, etc)
- In Blender, I use the addon to import the CC FBX model, which works fine. However, defaults material are "advanced" node setup, which I don't want. I would like to use "basic" setup.
- I select "Basic" then rebuild => Error (see attached screenshot).

Could you please have a look and correct if this is a bug in the addon?

![Error rebuild material](https://user-images.githubusercontent.com/83834558/191508248-c2e367c6-44d3-4840-88c1-6ecaf7f52923.jpg)

**Comment by muratak18** [comment]
I'm having the same issue. Please help!

**Comment by Remtou** [comment]
I just tested it. Works fine for me now. Thanks for the update!

**Comment by ne3lob** [comment]
Hello everyone . I still have the same error( what I can do with it? thank you

**Comment by soupday** [comment]
On the latest version (1.5.1) ?

**Comment by ne3lob** [comment]
Yes :( Also I am using the skin gen in cc3 , can it be a problem ?

![Blender 12_6_2022 10_14_38 PM](https://user-images.githubusercontent.com/75087259/206024625-800f2d95-621c-4126-862c-7ef0107137d7.png)
![Blender Preferences 12_6_2022 10_12_59 PM](https://user-images.githubusercontent.com/75087259/206024660-319ad9c0-7481-4861-8b0e-b54602caf996.png)

**Comment by soupday** [comment]
Ok, quick fix time. A missing normal map was indirectly causing a script error.

Try [1.5.2](https://github.com/soupday/cc_blender_tools/releases/tag/1_5_2)
