### ISSUE TITLE
Error: "Failed to load the File" with CC4 Transformer Daz character 

### ISSUE THREAD

**Issue by CloudNinja5** [soupday/cc_blender_tools#103]
I can successfully use the plug-in on a standard, CC4 character e.g. Kevin that I've "round-tripped" from CC4 to Blender and then back to CC4 when using the CC4 Menu/PlugIns/Blender Pipeline/ Import character from Blender.

However, my character is a Genesis 8 character imported into CC4 via the Transformer which was then modified in CC4, exported to Blender from CC4 using all the recommended Blender export settings (mesh, no embed, etc); imported into Blender via your CC/iC Pipeline tool (import character, etc) - then exported using the "Export to CC3/4" button.

When I goto round-trip back to CC4 via using the PlugIns/Blender Pipeline/ Import character from Blender - then click "Import Character" button, then click "OK" on the next "Create Assets(s) dialog - it starts to load the FBX file and then I get the error "Failed to load the File". 

![image](https://user-images.githubusercontent.com/114263101/192061482-cec6408a-927a-4b53-a060-c6066409ccbf.png)

Using a Windows 10 PC; CC4; Blender 3.1.2 

Thank you for creating this amazing PlugIn :0).

**Comment by soupday** [comment]
There is a case where this error happens if the character does not have the Tearline and Eye Occlusion meshes. I don't think the Daz transformer adds them?

You can add re-add them to the character from the modify panel 'Add Eye Element'

**Comment by CloudNinja5** [comment]
Perfect - ty! I really appreciate the quick response,

**Comment by CloudNinja5** [comment]
This might be a fringe case BUT I get the same error if I delete the mesh in Blender and only have the Head.

Is there a way to have your plugin work for a head bust only?

with appreciation,
.cn
