### ISSUE TITLE
CC4 head only error: "Fail to Load" 

### ISSUE THREAD

**Issue by CloudNinja5** [soupday/cc_blender_tools#105]
I have a CC4 character but with only the head in Blender - then exported as fbx. When back in CC4 , I'm getting the error: "Fail to load the file" using the CC4 Menu/PlugIns/Blender Pipeline/ "Import character from Blender".

Is there a way to have your plugin work for a head bust only?

with appreciation,
.cn

**Comment by soupday** [comment]
Short answer is: No.

It's the full body mesh or nothing.

**Comment by CloudNinja5** [comment]
Ok - ty for clarifying
