### ISSUE TITLE
Unable to import to CC4 after Rigify setup

### ISSUE THREAD

**Issue by kybak** [soupday/cc_blender_tools#107]
Description:
After applying the Rigify setup to my model in Blender I am unable to re-import it back into CC4. Would appreciate some help with this if it's my fault.

Steps to reproduce:

1. Export FBX from CC4 w/ Blender Pipeline plugin
2. Import FBX to Blender w/ CC Pipeline plugin
3. Click Rigify in CC Pipeline plugin
4. Select all
5. Export to CC3/4 (plugin)
6. Import to CC4 w/ Blender Pipeline Plugin

Result: Error -> "Failed to load the file".

**Comment by soupday** [comment]
Once the character has been Rigified you can't export it back into Character Creator (at least as a standard character), as the Rigify process completely changes the character armature.

Why do you need to export the Rigified character back to CC4?

**Comment by kybak** [comment]
Got it, thanks. I had rigged the model to be able to change their pose for sculpting purposes and it would have been nice to reimport back to CC4 to make any changes there that I forgot to make initially. For instance, some of the morphing sliders in CC4 are easier to use than manipulating the mesh in blender. I figured out a different flow, just wanted to make sure that wasn't an option.
