### ISSUE TITLE
Rigify Retarget Preview works, Baking fails

### ISSUE THREAD

**Issue by taigadigital** [soupday/cc_blender_tools#112]
Blender 3.3.1 LTS and the latest plugin version (1.4.9)

Seem to be running into an issue where an animation retarget will preview just fine, but when Baking Retarget the Rigify armature will only accept the shape keys, not the bones.

**Comment by soupday** [comment]
Need more information as I am not seeing this happen.

**Comment by taigadigital** [comment]
Yeah, sorry. I went to record a video and interestingly it is working now. The only thing that has changed was a system reboot. So I can't say what trouble I might have been coming across.

**Comment by taigadigital** [comment]
Re-opening this ticket as this issue has appeared once in again in Blender 3.4x. It does _not_ appear to occur in Blender 3.3x LTS.

**Comment by soupday** [comment]
Ok, I see it. Blender 3.4 needs to have the armature in pose mode before invoking the bake operator when baking to 'only selected' bones, otherwise it just makes an empty action.

Simple enough to fix: Try version 1.5.3 see if that solves the problem.

**Comment by taigadigital** [comment]
Latest attempt to Preview Retarget while in Pose Mode also resulted in an error in 3.4.1. In Object Mode and in Pose Mode, Rest, and Posed. This is a Rigify armature made directly from a CC mesh with the CC/iC tool.

```
bpy.ops.cc3.rigifier(param="RETARGET_CC_PAIR_RIGS")
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cc_blender_tools-1_5_2\rigging.py", line 2950, in execute
    adv_preview_retarget(self, chr_cache)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cc_blender_tools-1_5_2\rigging.py", line 1836, in adv_preview_retarget
    retarget_rig = adv_retarget_pair_rigs(op, chr_cache)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cc_blender_tools-1_5_2\rigging.py", line 1879, in adv_retarget_pair_rigs
    adv_retarget_remove_pair(op, chr_cache)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cc_blender_tools-1_5_2\rigging.py", line 1827, in adv_retarget_remove_pair
    reset_shape_keys(chr_cache)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cc_blender_tools-1_5_2\rigging.py", line 1977, in reset_shape_keys
    if obj.type == "MESH":
AttributeError: 'NoneType' object has no attribute 'type'

```

**Comment by soupday** [comment]
had you deleted anything from the character before hand?

**Comment by soupday** [comment]
Blender does like to hang on to old object data, I'll put in some more robust checks when referencing objects, so deleting objects is safer.

You can clean up old armatures and actions, and everything else from the Blend File Outliner: (There should be one in the Scripting workspace)

![Outliner-BlendFile](https://user-images.githubusercontent.com/79094830/216362252-24bca003-6887-4ece-b1fc-4802b97e07d0.jpg)

**Comment by taigadigital** [comment]
Cheers!
