### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'generation'

### ISSUE THREAD

**Issue by Becmuda1704** [soupday/cc_blender_tools#114]
Got this when I'm trying to export my character, do you guys know where the problem is? Thank you!

![image](https://user-images.githubusercontent.com/116052175/203638549-aafb663d-0d42-4b59-b58a-5b399bc9f4c6.png)

**Comment by soupday** [comment]
See if 1.5.1 fixes it.

**Comment by Becmuda1704** [comment]
> Was able to reproduce this, and a few other related bugs.
> 
> See if 1.5.1 fixes it.

Working like a charm now, thank you so much!
