### ISSUE TITLE
eyes' bone and eyeball scale mess up after imported 

### ISSUE THREAD

**Issue by MOTO4GIT** [soupday/cc_blender_tools#132]
![20230228_013340](https://user-images.githubusercontent.com/119428782/221640268-8404246d-7b1d-465e-a789-0fc6a69c59e9.jpg)

**Comment by soupday** [comment]
The add-on doesn't do anything to the bones, scales or animation sequences, it just runs the FBX importer and sets up the materials. (Unless you've Rigified and retargetted of course.)

Check that iClone is exporting the correct bone positions for the eyes. Do you have anything controlling the eyes in iClone (look at targets or something like) that might not be exporting correctly?

**Comment by MOTO4GIT** [comment]
> The add-on doesn't do anything to the bones, scales or animation sequences, it just runs the FBX importer and sets up the materials. (Unless you've Rigified and retargetted of course.)
> 
> Check that iClone is exporting the correct bone positions for the eyes. Do you have anything controlling the eyes in iClone (look at targets or something like) that might not be exporting correctly?

But the 1.5.3 plug works fine, the eyes have only been messed up in 1.5.4
