### ISSUE TITLE
"Bake retarget" does not bake the animation

### ISSUE THREAD

**Issue by alebnn** [soupday/cc_blender_tools#162]
Hi, I don´t know what I´m doing wrong here, but maybe somebody can guide me in the right direction. 
I already loaded both the character and the animation, and when I press the "Preview Retarget" button, it looks great, everything moves as it supposed to. But when I press the "Bake Retarget" button, after a while my character goes back to static pose... no animation. Any ideas? Thank you very much in advance!

CC Addon: 1.6.0
Blender 3.5.1

**Comment by alebnn** [comment]
Version 1.5.5 works as it supposed to

**Comment by soupday** [comment]
If it doesn't work in 1.6.0 that's a problem.

From what I can tell it is baking the animation into a new action, it's just not assigning it to the rig after it's baked. Looking into it.

**Comment by soupday** [comment]
Try [1.6.0.1](https://github.com/soupday/cc_blender_tools/releases/tag/1_6_0_1)

**Comment by alebnn** [comment]
> Try [1.6.0.1](https://github.com/soupday/cc_blender_tools/releases/tag/1_6_0_1)

This works fine too, it was obviously an issue with 1.6.0

Thanks
