### ISSUE TITLE
'Reallusion/Amplify/RL_SkinShader_Variants_URP' uses 37 texture parameters, more than the 32 supported by the current graphics device.

### ISSUE THREAD

**Issue by kzinnia** [soupday/cc_blender_tools#174]
I received the following message on my Android device.

2023-07-22 23:45:16.198 8982 9084 Warn Unity Shader 'Reallusion/Amplify/RL_SkinShader_Variants_URP' uses 37 texture parameters, more than the 32 supported by the current graphics device.

Please check.
Thank you!

**Comment by soupday** [comment]
The full wrinkle enabled shader uses 30 textures. Adding Unity's internally used light maps, shadow maps, depth maps etc, it can easily go over a 32 texture parameter limit.

Your options are: 

- Turn off wrinkle maps in the shader features.
- Or, bake the character using the bake function. This will combine and pack the textures and reduces it to 22 textures, which should stay under the limit.
