### ISSUE TITLE
"RL Hair shader" doesn't receive light from Spot Light (Second Light) on mobile

### ISSUE THREAD

**Issue by kzinnia** [soupday/cc_blender_tools#176]
![SpotLightError](https://github.com/soupday/cc_blender_tools/assets/85612373/562f08a1-b75e-49f0-a826-c27fe68570af)

As shown in the attached picture, "RL Hair shader" doesn't receive light from the Spot Light on mobile (Android Build). 
However, it looks fine in the Unity editor.

Spot Light is Second Light.
I tried to chage type of spot light to dir light, but it doesn't work.

Please Check.

**Comment by soupday** [comment]
Which version of Unity? And which version of the Unity tools package?

Also this is the repository for the Blender tools. Unity issues should be reported in the relevant cc_unity_tools repo.

**Comment by kzinnia** [comment]
I will post this with more information in cc_unity_tools repo. thank you!
