### ISSUE TITLE
Fbxkey won't generate anymore

### ISSUE THREAD

**Issue by diablo85xxx** [soupday/cc_blender_tools#208]
I made a character in CC4 and exported in blender via CCtool plugin in fbx format.

With this fbx, i imported in blender with this cc blender tool, and everythings was ok... I made several change and adjustements on my char, and it correctly exported back to CC4, using the proper fbxkey.

But now, all of a sudden, the plugin doesn't update the fbxkey file anymore (the fbx and json are updated correctly). Thus now can't import back to CC4 anymore because it crash without the proper updated fbxkey file...

Can't see any fix online... Could someone help me?

**Comment by soupday** [comment]
The addon doesn't update the fbxkey, in fact you can't update it as it's encypted. 

It just copies it from the original fbxkey (exported from CC4), if it's exported to a different directory or with a different name.

As long as you have that original fbxkey exported by CC4, you can reimport it back into CC4.

**Comment by diablo85xxx** [comment]
Ok, thanks to your comment, i figured out that the crash on CC4 it happens for a problem on my mesh.
