### ISSUE TITLE
Strange facial deformation when using rigify

### ISSUE THREAD

**Issue by cuddlyogre** [soupday/cc_blender_tools#213]
When rigifying with facial rig, there is a strange pointiness to the mouth. This can be largely corrected by setting the **Copy Transforms** bone constraint **Influence** value of **MCH-jaw_master.001** from **0.75** to **0.9**
![image](https://github.com/soupday/cc_blender_tools/assets/3506795/6e7f5296-ba66-4e63-980c-d097c6548186)
![image](https://github.com/soupday/cc_blender_tools/assets/3506795/b71164f6-20f4-49e6-8563-2121643b7b15)

Not building the facial rig prevents the pointy mouth, but causes the wrong values for the eyelid drivers.
![image](https://github.com/soupday/cc_blender_tools/assets/3506795/4821d3fe-069d-47ed-b427-70786df8c77f)
![image](https://github.com/soupday/cc_blender_tools/assets/3506795/ea6c6164-0d53-4017-a36e-90c17b8110ff)

The cause of the bad driver values is due to these bones having a roll value of zero instead of the roll value of their metarig bones, which is around 143.
```
                    eyes = {
                        "eye.L": [
                            "master_eye.L",
                            "MCH-eye.L",
                            "ORG-eye.L",
                            "DEF-eye.L",
                        ],
                        "eye.R": {
                            "master_eye.R",
                            "MCH-eye.R",
                            "ORG-eye.R",
                            "DEF-eye.R",
                        }
                    }
```

This can be corrected by recalculating the bone roll with **Shift+N** and choosing **Global +Z Axis**
![image](https://github.com/soupday/cc_blender_tools/assets/3506795/c62467e1-d570-4b1d-8f3e-615bebd1c14b)

**Comment by soupday** [comment]
There's been a few cases now, where the Rigify process is not honouring the bone roll of the meta-rig. I corrected the eye bone roll in the meta-rig specifically to stop this happening, but Rigify seems to be ignoring the roll since Blender 4.0. Maybe even before that.

The jaw bone can generate at odd angles even though that's been corrected in the meta rig also.

Unless...

**Comment by soupday** [comment]
Unless Rigify is applying it's own correction now and the two corrections are cancelling each other out or adding together and over compensating.

Removing the roll corrections from the meta-rig and regenerating the Rigify: These bones in the correct alignment now.

This strangely complicates things.

**Comment by cuddlyogre** [comment]
I'm using 2.0.5 and the facial deforms are now very strange with and without a facial rig. Using both extended and standard expression sets made no difference.
![image](https://github.com/soupday/cc_blender_tools/assets/3506795/c3b93729-90e1-4e78-afd7-3096b90c5dc1)

**Comment by soupday** [comment]
Because the jaw should have been aligned to -Z, not +Z, which reversed the sign on the Jaw Open shapekey driver...

Emergency surgery on 2.0.5: now [2.0.5c](https://github.com/soupday/cc_blender_tools/releases/tag/2_0_5c)

**Comment by cuddlyogre** [comment]
You're my hero! The problem is resolved.

Thank you for your quick action.
