### ISSUE TITLE
Weird eye color

### ISSUE THREAD

**Issue by kei971031** [soupday/cc_blender_tools#214]
Hello, I'm using Blender 4.0 and Character Creator 4.

My charactor from CC4 has problem with eye .

![white_eye](https://github.com/soupday/cc_blender_tools/assets/87850850/399e21b5-1ec7-43b4-bd52-34a4c94f32b3)

Here is eye shader.
![shader](https://github.com/soupday/cc_blender_tools/assets/87850850/801bc7b5-a695-451e-befc-f1cc1d50404e)

And here is my model.
https://drive.google.com/file/d/12BgziIZxc4vBBEEPCebZkw6LVW2k3-CR/view?usp=drive_link

This model using default eye model of CC4 named "CC_Base_Eye"
What should I check? I would greatly appreciate your assistance in this matter.

**Comment by kei971031** [comment]
After adjusting the parameters and testing several times, it seems that sclera is the problem.

In the picture below, the eye on the left (right in the image) has Sclera Scale set to 0.001.

For the right eye (left in the image), in order to avoid using the problematic Sclera, a new Principled BSDF was created and only Diffuse Color and Metallic were assigned.

For now, using Principled BSDF seems plausible, so we're working that way.

![eye2](https://github.com/soupday/cc_blender_tools/assets/87850850/d0d4f1ff-1cad-4331-b235-603b15e29591)

**Comment by soupday** [comment]
Version 1.3.8 of the add-on is very old, almost two years old now and isn't compatible with the changes in Blender 4.0+
Use the latest version (currently [2.0.5](https://github.com/soupday/cc_blender_tools/releases)).

**Comment by kei971031** [comment]
Oops. I didn't realize I was using an old version. I'm so sorry for wasting your time. Thank you!
