### ISSUE TITLE
Geometry showing in Cycles render

### ISSUE THREAD

**Issue by tswallen** [soupday/cc_blender_tools#23]
Hey there!

I rendered a character in Cycles (plugin set to Cycles textures) using a lighting setup (no HDR) and the result is attached. Any idea why we are seeing jagged edges and lines on her arms, shoulders, chest and legs? I only see this in the render and not in the preview window.

P.S. an artist and I are interested in working on some things with you, could you please provide a way for us to get in touch? My email is tom@quantumimage.io

![hero](https://user-images.githubusercontent.com/9687599/136714482-7594b26c-926b-4603-9439-94dc0c58b93d.jpg)

**Comment by soupday** [comment]
I did a test render of a similar image:

![TestBcycles1and2](https://user-images.githubusercontent.com/79094830/136813231-b7ac6f67-16fe-4ffb-a0e5-02245dced800.jpg)

You can see similar edge artefacts in the left hand image on the ridge of the nose, around the neck and on the arms.

The offset does resolve these artefacts, but it does also make the shadows a little darker.

**Comment by tswallen** [comment]
Any update on the above? Keen to contact you :)

**Comment by soupday** [comment]
The messaging on the Reallusion forums should work: https://forum.reallusion.com/Users/2891183/VictorSoupday

Keep in mind I'm really busy at the moment, barely have enough time for my own projects.

**Comment by tswallen** [comment]
It says on the forum I need 2 approved posts before I can PM you. It sucks. Do you have social media or another channel? You can email me: tswallen@outlook.com with any private information like Facebook, Instagram or LinkedIn. We're really in need of some guidance and I expect it to take no more than 2-3 hours. Just need help with SkinGen and improving our Blender renders/textures. I understand you're busy but we'll make this well worth your time and on your own terms.
