### ISSUE TITLE
Wrinkle drivers often breaking

### ISSUE THREAD

**Issue by loicbramoulle** [soupday/cc_blender_tools#266]
Hi, sorry as this is not an exact issue with the pipeline, but I keep having the wrinkle system breaking in Blender.
The head mesh didn't change, so I don't see how that happens.
But would there be any workaround to re-link these drivers ?
Maybe it's when migrating the file to another blender version.
The names seem correct, dunno why it lost connection:
![image](https://github.com/user-attachments/assets/42f344d6-a191-4571-b0c1-4cec36752893)
Many thanks for any idea on how to reconnect those.

**Comment by loicbramoulle** [comment]
Damn my mistake, I've separated the head, instead of separating the body. so the mesh name has changed, and I deleted the shapes on the body.

**Comment by soupday** [comment]
I should really try to account for this situation. There are times the mesh really needs to be separated and the build material / driver system needs to recognize and cope with split or duplicated and replaced meshes. So if you do break the drivers accidentally, rebuilding the materials would fix it, or maybe just a rebuild drivers / modifiers button.

**Comment by loicbramoulle** [comment]
wow amazing if that's possible in the future. Right now I've re-merged the head onto the body, then separated the body, so wrinkles were connected to the head mesh again. I just had to force-refresh them by going in the driver editor, trying to copy paste, ctrl+Z, click force refresh dependencies, do a random action, and suddenly they all connected again (red lines gone).
So blender bugs a bit with that, but shuffeling it a bit did reconnect the drivers.
