### ISSUE TITLE
blender 3.0 and 3.1 not working export to cc3

### ISSUE THREAD

**Issue by vvp3** [soupday/cc_blender_tools#70]
1. I exported a simple char form cc3
2. i imported with the addon in blender

result: My button for export for cc3 is greyed out
hence, everything I do is in vain as I cannot export it for cc3.

**Comment by soupday** [comment]
There are only two possible reasons why the export button greys out.

1. The character does not have an FbxKey.

The FbxKey is generated with the export from CC3, by exporting the character as **Mesh Only**, or **Mesh and Motion** in **Calibration** pose. _No other options will generate an FbxKey._ 

GameBase or InstaLod/Merged material characters will not generate an FbxKey and cannot be exported backed to CC3.

If the .Fbxkey file is not there along with the character .fbx, the character cannot be exported back to CC3 so the button is greyed out.

2. The character was not imported using the **Import Character** button in the CC3 add-on panel.

I've seen some people try to import the character using the File > Import > FBX menu. The add-on will not recognise the character if you do this. 

If you did do this (and you have the .Fbxkey too), you can just export the character manually from Export > FBX menu. (Default settings except: "Only selected" and _uncheck_ "add leaf bones")
