### ISSUE TITLE
Issue with Hair

### ISSUE THREAD

**Issue by dalemayphoto** [soupday/cc_blender_tools#8]
I've tried the latest version of cc3_blender_tools and I am blown away with what you've done. I hardly have to adjust any of the materials after import. Truly stunning.

I do however have an issue with most of the hair I import. I've tried setting the material to Hashed but I'm still having issues in Cycles Render. I've attached a screen shot of my Material Preview, Render Preview and an actual render in Cycles.

Please let me know if you have any idea what is causing the issue or if you can tell me how to adjust the materials to fixe the issue.

![Previews](https://user-images.githubusercontent.com/76479054/117500487-b55ace80-af4a-11eb-9b5c-39be953bbb5d.jpg)

**Comment by soupday** [comment]
It's the transparency bounces. The more overlayed transparencies you have, the more bounces you need for the ray tracing to penetrate through the hair layers to the scalp. Try setting the Max Transparency Bounces to something really high like 50.

![tbounce](https://user-images.githubusercontent.com/79094830/117513078-d80bd800-af88-11eb-8b75-e76f834beee5.png)

**Comment by soupday** [comment]
Maybe I should set this automatically if detects smart hair meshes...

**Comment by dalemayphoto** [comment]
Thank you, I just tried it and it looked much better. Setting it automatically might be helpful although most Blender users with more experience than myself might know this already. You did such an amazing job with this add-on.
