### ISSUE TITLE
Rigify Setup

### ISSUE THREAD

**Issue by JC0NN0R** [soupday/cc_blender_tools#81]
I don't think the rig is being setup properly. The Arms are stretching and doing funny things and none of the other components seem to be working properly...the heads coming off leaving the teeth behind...the pelvis is rotating with the FK leg components but leaving the legs behind

![image](https://user-images.githubusercontent.com/53392450/170803703-d5648224-dc1e-445d-8021-b66892a2b178.png)

**Comment by JC0NN0R** [comment]
Ok I can see that the issue is that no constraints are being added....also I might add that when I rotate the FK components nothing happens...and when I rotate the neck the head doesn't move with it...they aren't chained together properly

**Comment by JC0NN0R** [comment]
Btw I thought I would that I am exporting as shown in the Reallusion Video 
![image](https://user-images.githubusercontent.com/53392450/170804409-5a194b5a-a8dd-446e-bec1-f34883777676.png)

**Comment by soupday** [comment]
see response: https://forum.reallusion.com/FindPost516225.aspx
