### ISSUE TITLE
UV mirroring setting is lost

### ISSUE THREAD

**Issue by dantreble** [soupday/cc_blender_tools#9]
Again, thanks for the plugin, it's amazing.

For some reason a lot of our textures end up with a V mirror. Importing as fbx honors this and inserts a vector transform node on the uv, sadly this is lost when importing through this plugin.

**Comment by soupday** [comment]
This presents something of a problem...

In CC3 each texture can be individually tiled, mirrored, offset and rotated. The FBX format only contains information for the few textures it understands, namely the diffuse, specular, opacity and normal textures. This means there is **no** data for the roughness, metallic nor _any_ of the secondary textures (color blend, blend normals etc...).

I can detect the mappings on the image texture nodes as imported by the initial FBX import, so the question becomes: is it safe to assume if there is mapping on the diffuse map then that same mapping should be applied to all the textures in that material?

Is this happening just for clothing/accessory meshes?

**Comment by dantreble** [comment]
> is it safe to assume if there is mapping on the diffuse map then that same mapping should be applied to all the textures in that material?

For all the cases I've come across in the wild, yes. I understand it isn't totally correct and never can be given the file format.

> Is this happening just for clothing/accessory meshes?

I've seen it happen on the body textures as well.

Thanks for looking into it!
