### ISSUE TITLE
Import materials and apply original if available

### ISSUE THREAD

**Issue by schroef** [soupday/cc_blender_tools#98]
I just saw this great addon [on CGDive youtube](https://www.youtube.com/watch?v=XsAT3s8nrPE) channel. He showed a great use case for this add-on.
One thing i noticed is that there is no option when importing, to check for existing materials. Currently it adds all materials as copies. It would be great if it could find use available mats.

I can try to make this adjustment myself and pull request

**Comment by soupday** [comment]
Since version 1.4.3 it does. (It's an option in the Character Build Panel, but it's on by default) It's a de-duplication process, so any textures that are identical are re-used rather than copied then any materials with the same name, that use the same textures and have the same parameters are re-used rather than duplicated. Any differences will force a new material.

**Comment by schroef** [comment]
Thanks for the fast reply!

I guess it happened when he exported it initially and the dot named materials got their underscore.
Ill test that model he showed and see where it happens

thanks for the headsup on that dev branch

**Comment by soupday** [comment]
Reallusion's software doesn't like dots in the mesh/material names so it always replaces them with underscores.
Also, I discovered only a few weeks ago, that if the material name starts with a digit, that digit gets replaced with an underscore too.

Causes havok with name matching.

**Comment by schroef** [comment]
"I've made a preliminary operator function to do this matching. It's in the Utilities panel of the CC/iC Create Tab and I've put a button in the Rigify panel in the info box (when the character is detected as ActorCore)"

what is the name of this operator if may ask?

**Comment by schroef** [comment]
> Reallusion's software doesn't like dots in the mesh/material names so it always replaces them with underscores. Also, I discovered only a few weeks ago, that if the material name starts with a digit, that digit gets replaced with an underscore too.
> 
> Causes havok with name matching.

So user needs make it a habbit of properly naming meshes and materials so they get imported correctly in return. Ill make a comment about that below his video/

**Comment by soupday** [comment]
It's part of the CC3OperatorCharacter (id "cc3.character")

https://github.com/soupday/cc_blender_tools/blob/Dev/characters.py#L804

**Comment by soupday** [comment]
> .



> So user needs make it a habbit of properly naming meshes and materials so they get imported correctly in return. Ill make a comment about that below his video/

To be safe, yes. Well named objects/meshes/materials should guarantee successful results.

**Comment by schroef** [comment]
Really appreciate you guys even replying over the weekend!!!

i added the info about the material to his video,. hope it helps others

**Comment by schroef** [comment]
> It's part of the CC3OperatorCharacter (id "cc3.character")
> 
> https://github.com/soupday/cc_blender_tools/blob/Dev/characters.py#L804

So its the match_materials operator i guess
